pipeline {
    agent any

    stages
    {
        stage('Unit Tests - Backend')
        {
            agent 
            {
                docker
                {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment
            {
                HOME = "${WORKSPACE}"
                GOCACHE = "${WORKSPACE}/.gocache"
                GOMODCACHE = "${WORKSPACE}/.gomodcache"
            }
            steps
            {
                dir('bugtracker-backend')
                {
                    sh '''
                    id
                    echo HOME=$HOME
                    echo WORKSPACE=$WORKSPACE
                    go env
                    '''
                    sh 'go test -v ./...'
                }
            }
        }
    }
}